[package]
name = "LineCloser"
$10.1.1"
edition = "2021"

[dependencies]
clap = { $10.1.1", features = ["derive"] }
sysinfo = "0.30.12"
windows = { $10.1.1", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

