[package]
name = "LineCloser"
version = "0.1.5"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
sysinfo = "0.30.12"
windows = { version = "0.58.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
